version: 2
jobs:
  test:
    docker:
      - image: circleci/python:3.6-stretch-node
        environment:
          DJANGO_SETTINGS_MODULE=timetracker.settings.production
          SECRET_KEY=testingsecretkey
          SECURE_SSL_REDIRECT=false
          ALLOWED_HOSTS=localhost
    steps:
      - checkout
      - run:
          name: install python dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install flake8 isort
            pip install -r requirements.txt
      - run:
          name: install node dependencies
          command: |
            npm install --quiet
      - run:
          name: compile static assets
          command: |
            make static
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            flake8 ./timetracker
            isort --recursive --check-only --diff ./timetracker
            django-admin collectstatic --clear --noinput
            django-admin makemigrations --check --noinput
            django-admin check
            django-admin test
workflows:
  version: 2
  build_and_test:
    jobs:
      - test
