# Generated by Django 2.2 on 2019-04-04 13:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSheetGeneratedFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='timesheet_exports', verbose_name='file')),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='generated at')),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='sheets.TimeSheet', verbose_name='sheet')),
            ],
            options={
                'verbose_name': 'time sheet file',
                'verbose_name_plural': 'time sheet files',
            },
        ),
    ]
